kind: Service
apiVersion: v1
metadata:
  name: msa-apigw-service
spec:
  type: LoadBalancer
  selector:
    app: msa-apigw
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: msa-apigw
  labels:
    app: msa-apigw
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-apigw
  template:
    metadata:
      labels:
        app: msa-apigw
        version: "1.0.0-RELEASE"
    spec:
      containers:
      - name: msa-apigw
        image: docker.gsp.sicc.co.kr/apigw:1.0.1-RELEASE
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prd
        - name: spring.cloud.config.uri
          value: http://100.70.69.238:8888
        ports:
        - name: http
          containerPort: 9090
